### ISSUE TITLE
ReducerBuilder 네이밍 관련

### ISSUE THREAD

**Issue by namenu** [ridi/react-webviewer#41]
https://github.com/ridi/react-webviewer/blob/master/src/util/ReducerBuilder.js

`ReducerBuilder` 클래스의 이름이 실제 기대하는 동작과 다릅니다.

**기대하는 의미**
 - Reducer 자체를 생성해주는 클래스 (`StringBuilder`가 연상됨)

**실제 동작**
 - Key-Value 기반으로 변경된 state를 반환하는 클래스

오픈소스로 관리하고 있는 만큼, reducer의 일반적인 의미를 지켜서 사용할 필요가 있다고 생각합니다.

PS.
원래의 의도는 Immutable을 업데이트 하기 위한 Helper 클래스의 작성이었다고 추측이 되는데요,
공식 문서에는 `dot-prop-immutable`, `immutability-helper` 등을 권장하고 있습니다.
https://redux.js.org/docs/recipes/reducers/ImmutableUpdatePatterns.html#immutable-update-utility-libraries

**Comment by kyungmi** [comment]
@namenu 말씀해주신대로 단순 state 변동만을 담당하고 있지만 본래 Redux에서 reducer가 하는 일이 "유입된 action과 기존 state"(input)를 기반으로 "새로운 state"(output)를 반환하는 일이므로 의미가 통한다고 생각합니다.
하지만 혼동되는 부분이 있다면 변경해도 크게 상관은 없을 것 같습니다.

**Comment by kyungmi** [comment]
@namenu 말씀해주신대로 리듀서의 일부 기능을 돕는 클래스이기 때문에, helper등의 이름으로 변환하는 것이 좋겠다는 생각이 듭니다.
