### ISSUE TITLE
Using `prop-types` package instead of `react`'s `PropTypes`

### ISSUE THREAD

**Issue by kyungmi** [ridi/react-webviewer#5]
I get the following warning when using this component:

Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

It would be better to use `prop-types` package for the next version of react.

**Comment by Jaeyo** [comment]
@kyungmi fixed with version 0.1.5
