### ISSUE TITLE
Prevent from changing `isFullScreen` state to true, when settings popup is opened.

### ISSUE THREAD

**Issue by kyungmi** [ridi/react-webviewer#6]
I used `isFullScreen` state to hide and show Header, Footer, and "Settings" popup.

If I modify the line height value via this "Settings" popup, `scroll` event will be occurred and `isFullScreen` state become true. And then "Settings" popup, Header and Footer are closed as I mentioned. 
Is there any way to prevent changing `isFullScreen` value to `true` for a while even if `scroll` event is occurred?

**Comment by Jaeyo** [comment]
@kyungmi `ignoreScroll` props is added to ViewerScreen in version 0.1.4. set `ignoreScroll={true}` when setting popup is opened.
